"""Read-only helpers for artifacts generated by 5g-Ansible.

Deployment execution and capability decisions live in 5g-Ansible. SynthRAN
parses the generated inventory only to address experiment probes and workloads.
"""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
from pathlib import Path
import re
import shlex
from typing import Any, Mapping, Sequence

from synthran.adapters.fiveg import FiveGAdapter, FiveGAdapterError
from synthran.dependencies import DependencyError, load_lock


SECTION_RE = re.compile(r"^\[([^]]+)]$")


class FiveGAnsibleError(FiveGAdapterError):
    """Raised when an upstream-generated experiment artifact is malformed."""


@dataclass(frozen=True)
class InventoryHost:
    name: str
    variables: Mapping[str, str]


@dataclass(frozen=True)
class NetworkInventory:
    """Read-only facts extracted from a 5g-Ansible generated inventory."""

    path: Path
    sha256: str
    core_node: InventoryHost
    ran_node: InventoryHost
    all_vars: Mapping[str, str]
    ue_hosts: Mapping[str, InventoryHost]

    @property
    def core(self) -> str:
        return self.all_vars["core"]

    @property
    def ran(self) -> str:
        return self.all_vars["ran"]

    @property
    def radio(self) -> str:
        return self.all_vars["rru"]

    @property
    def monitoring_enabled(self) -> bool:
        return self.all_vars.get("monitoring_enabled", "false").strip().lower() in {
            "true",
            "yes",
            "1",
        }

    def ue(self, name: str) -> InventoryHost:
        try:
            return self.ue_hosts[name]
        except KeyError as exc:
            raise FiveGAnsibleError(
                "selected physical UE is not present in the upstream inventory"
            ) from exc

    def redacted_summary(self) -> dict[str, Any]:
        return {
            "file_name": self.path.name,
            "sha256": self.sha256,
            "core": self.core,
            "ran": self.ran,
            "radio": self.radio,
            "core_node": self.core_node.name,
            "ran_node": self.ran_node.name,
            "co_located": self.core_node.name == self.ran_node.name,
            "monitoring_enabled": self.monitoring_enabled,
            "physical_ue_count": len(self.ue_hosts),
        }


@dataclass(frozen=True)
class DoctorCheck:
    name: str
    passed: bool
    detail: str


@dataclass(frozen=True)
class DoctorReport:
    checks: tuple[DoctorCheck, ...]
    mode: str = "offline"

    @property
    def ready(self) -> bool:
        return bool(self.checks) and all(check.passed for check in self.checks)

    def render(self) -> str:
        lines = [f"SynthRAN doctor ({self.mode})"]
        for check in self.checks:
            lines.append(
                f"[{'PASS' if check.passed else 'FAIL'}] {check.name}: {check.detail}"
            )
        lines.append(f"Result: {'READY' if self.ready else 'NOT READY'}")
        return "\n".join(lines)


def _parse_scalar(value: str, label: str) -> str:
    value = value.strip()
    if not value:
        raise FiveGAnsibleError(f"{label} must not be empty")
    try:
        tokens = shlex.split(value, comments=False, posix=True)
    except ValueError as exc:
        raise FiveGAnsibleError(f"{label} contains invalid quoting") from exc
    if len(tokens) != 1:
        raise FiveGAnsibleError(f"{label} must contain one scalar value")
    return tokens[0]


def _parse_host(line: str, section: str) -> InventoryHost:
    try:
        tokens = shlex.split(line, comments=True, posix=True)
    except ValueError as exc:
        raise FiveGAnsibleError(f"inventory section [{section}] has invalid quoting") from exc
    if not tokens:
        raise FiveGAnsibleError(f"inventory section [{section}] contains an empty host")
    variables: dict[str, str] = {}
    for token in tokens[1:]:
        if "=" not in token:
            raise FiveGAnsibleError(
                f"inventory host variables in [{section}] must use key=value"
            )
        name, value = token.split("=", 1)
        if not name or not value or name in variables:
            raise FiveGAnsibleError(
                f"inventory host variables in [{section}] must be unique and non-empty"
            )
        variables[name] = value
    return InventoryHost(name=tokens[0], variables=variables)


def _require_host_variables(host: InventoryHost, section: str, names: Sequence[str]) -> None:
    missing = [name for name in names if not host.variables.get(name)]
    if missing:
        raise FiveGAnsibleError(
            f"inventory section [{section}] is missing required host variables: "
            + ", ".join(missing)
        )


def parse_inventory(text: str, *, source: Path) -> NetworkInventory:
    """Parse upstream inventory facts without imposing a topology matrix."""

    sections: dict[str, list[str]] = {}
    current: str | None = None
    for number, raw_line in enumerate(text.splitlines(), start=1):
        line = raw_line.strip()
        if not line or line.startswith(("#", ";")):
            continue
        match = SECTION_RE.fullmatch(line)
        if match:
            current = match.group(1)
            sections.setdefault(current, [])
            continue
        if current is None:
            raise FiveGAnsibleError(
                f"inventory content before the first section at line {number}"
            )
        sections[current].append(line)

    hosts: dict[str, InventoryHost] = {}
    for section in ("core_node", "ran_node"):
        entries = sections.get(section, [])
        if len(entries) != 1:
            raise FiveGAnsibleError(
                f"inventory section [{section}] must contain exactly one host"
            )
        hosts[section] = _parse_host(entries[0], section)

    webshell_entries = sections.get("webshell", [])
    if len(webshell_entries) != 1 or _parse_host(
        webshell_entries[0], "webshell"
    ).name != "localhost":
        raise FiveGAnsibleError("inventory [webshell] must contain localhost exactly once")

    all_vars: dict[str, str] = {}
    for line in sections.get("all:vars", []):
        if "=" not in line:
            raise FiveGAnsibleError("inventory [all:vars] entries must use key=value")
        name, value = line.split("=", 1)
        name = name.strip()
        if not name or name in all_vars:
            raise FiveGAnsibleError("inventory [all:vars] names must be unique and non-empty")
        all_vars[name] = _parse_scalar(value, f"inventory variable {name}")

    required_vars = {
        "core",
        "ran",
        "rru",
        "core_node_name",
        "ran_node_name",
        "monitoring_enabled",
    }
    missing_vars = sorted(required_vars.difference(all_vars))
    if missing_vars:
        raise FiveGAnsibleError(
            "inventory [all:vars] is missing required variables: "
            + ", ".join(missing_vars)
        )

    core_node = hosts["core_node"]
    ran_node = hosts["ran_node"]
    if all_vars["core_node_name"] != core_node.name:
        raise FiveGAnsibleError("core_node_name must match the [core_node] host")
    if all_vars["ran_node_name"] != ran_node.name:
        raise FiveGAnsibleError("ran_node_name must match the [ran_node] host")
    common_host_variables = ("ansible_user", "nic_interface", "ip", "storage")
    _require_host_variables(core_node, "core_node", common_host_variables)
    _require_host_variables(ran_node, "ran_node", common_host_variables)

    ue_hosts: dict[str, InventoryHost] = {}
    for section in ("qhats", "qfits", "phones"):
        for line in sections.get(section, []):
            host = _parse_host(line, section)
            if host.name in ue_hosts:
                raise FiveGAnsibleError("physical UE appears in more than one inventory group")
            ue_hosts[host.name] = host

    return NetworkInventory(
        path=source,
        sha256=hashlib.sha256(text.encode("utf-8")).hexdigest(),
        core_node=core_node,
        ran_node=ran_node,
        all_vars=all_vars,
        ue_hosts=ue_hosts,
    )


def load_inventory(path: Path) -> NetworkInventory:
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        raise FiveGAnsibleError("inventory file was not found") from exc
    except (OSError, UnicodeDecodeError) as exc:
        raise FiveGAnsibleError("inventory file must be readable UTF-8 text") from exc
    return parse_inventory(text, source=path)


def run_offline_doctor(
    *, inventory_path: Path, lock_path: Path, dependency_root: Path
) -> DoctorReport:
    checks: list[DoctorCheck] = []
    try:
        inventory = load_inventory(inventory_path)
    except FiveGAnsibleError as exc:
        checks.append(DoctorCheck("inventory", False, str(exc)))
    else:
        checks.append(
            DoctorCheck(
                "inventory",
                True,
                f"{inventory.core} + {inventory.ran} + {inventory.radio}",
            )
        )

    try:
        lock = load_lock(lock_path)
    except DependencyError as exc:
        detail = str(exc)
        if detail.startswith("dependency lock not found:"):
            detail = "dependency lock was not found"
        checks.append(DoctorCheck("dependency-lock", False, detail))
        return DoctorReport(tuple(checks))

    checks.append(DoctorCheck("dependency-lock", True, "direct dependencies validated"))
    try:
        adapter = FiveGAdapter.from_lock(
            lock=lock,
            dependency_root=dependency_root,
            state_root=Path(".synthran/runs"),
            timeout_seconds=30,
        )
        capabilities = adapter.capabilities()
    except FiveGAdapterError as exc:
        checks.append(DoctorCheck("fiveg-ansible", False, str(exc)))
    else:
        checks.append(
            DoctorCheck(
                "fiveg-ansible",
                True,
                f"machine API ready ({len(capabilities.get('cores', []))} cores, {len(capabilities.get('rans', []))} RANs)",
            )
        )
    return DoctorReport(tuple(checks))
