name: synthran
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12.13
  - git=2.51.0
  - setuptools=83.0.0
  - paho-mqtt=2.1.0
  - pyarrow=21.0.0
  - ansible-core=2.20.5
  - openjdk=21.0.9
